### ISSUE TITLE
GeoLite2-ASN

### ISSUE THREAD

**Issue by jnovack** [wp-statistics/GeoLite2-Country#2]
This is a polite request for a GeoLite2-ASN repository. 

Would you kindly?

**Comment by mostafasoufi** [comment]
Good point, will do that

**Comment by mostafasoufi** [comment]
Done https://github.com/wp-statistics/GeoLite2-ASN

**Comment by jnovack** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/387006/167503044-339d8394-bada-41c1-828b-c0c1705ae0fa.png">

**Comment by mostafasoufi** [comment]
My bad, the repo is now public!

Thank you for reporting.

**Comment by jnovack** [comment]
We have all been there.  No problem.
